STELLAR_MODELS = [
    "IncidentEmission",
    "LineContinuumEmission",
    "TransmittedEmission",
    "EscapedEmission",
    "NebularContinuumEmission",
    "NebularEmission",
    "ReprocessedEmission",
    "IntrinsicEmission",
    "EmergentEmission",
    "TotalEmission",
    "CharlotFall2000",
    "PacmanEmission",
    "BimodalPacmanEmission",
]
