# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from typing import Any, Dict, List

# -- Project information -----------------------------------------------------

project: str = "synthesizer"
copyright: str = (
    "2024, Chris Lovell, Stephen Wilkins, Aswin Vijayan, Will Roper"
)
author: str = "Chris Lovell, Stephen Wilkins, Aswin Vijayan, Will Roper"
release: str = "0.3.0-beta"

# -- General configuration ---------------------------------------------------

# Adjusting the path to find the module
sys.path.insert(0, os.path.abspath("../../synthesizer"))
sys.path.insert(0, os.path.abspath("../../"))
sys.path.insert(0, os.path.abspath("../"))
sys.path.insert(0, os.path.abspath("."))

# Sphinx extensions
extensions: List[str] = [
    "nbsphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.autodoc",  # core library for html generation from docstrings
    "sphinx.ext.autosummary",  # create neat summary tables
    # Add a link to the Python source code for classes, functions etc.
    "sphinx.ext.viewcode",
    # Automatically document param types (less noise in class signature)
    "sphinx_autodoc_typehints",
    "IPython.sphinxext.ipython_console_highlighting",
    "sphinx_gallery.gen_gallery",
    "sphinx_toolbox.collapse",
]
# Configuration for sphinx-gallery
sphinx_gallery_conf: Dict[str, Any] = {
    "examples_dirs": "../../examples",  # path to your example scripts
    # Path to where to save gallery generated output
    "gallery_dirs": "auto_examples",
    "nested_sections": True,
    # Directory where function/class granular galleries are stored
    "backreferences_dir": "_autosummary/backreferences",
    # Modules for which function/class level galleries are created. In
    # this case sphinx_gallery and numpy in a tuple of strings.
    "doc_module": ("synthesizer"),
    #     # Regexes to match objects to exclude from implicit backreferences.
    #     # The default option is an empty set, i.e. exclude nothing.
    #     # To exclude everything, use: '.*'
    #     # 'exclude_implicit_doc': {r'pyplot\.show'},
}

# -- Other configurations -----------------------------------------------------

# Turn on sphinx.ext.autosummary
autosummary_generate: bool = True

# Remove 'view source code' from top of page (for html, not python)
html_show_sourcelink: bool = False

# If no docstring, inherit from base class
autodoc_inherit_docstrings: bool = True

# Enable 'expensive' imports for sphinx_autodoc_typehints
set_type_checking_flag: bool = True

# Continue through Jupyter errors
nbsphinx_allow_errors: bool = True

# Paths relative to the configuration file
templates_path: List[str] = ["templates"]
html_static_path: List[str] = []

# exclude .py and .ipynb files in auto_examples generated by sphinx-gallery
# this is to prevent sphinx from complaining about duplicate source files
exclude_patterns = [
    "auto_examples/**/*.ipynb",
    "auto_examples/**/*.py",
]


# Main document name
master_doc: str = "index"

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# HTML output options
html_logo: str = "synth.png"
html_theme: str = "furo"
html_theme_options: Dict[str, Any] = {
    "sidebar_hide_name": True,
}

html_title = "Synthesizer"
